config/initializers/airbrake.rb

This mimics the multipage-frontend configuration. The credentials are stored in env variables.

Errbit configuration

---

app/helpers/service_manual_topic_helper.rb
app/views/content_items/service_manual_topic.html.erb
test/helpers/service_manual_topic_helper_test.rb
test/integration/service_manual_topic_test.rb

We have implemented communities in the topic sidebar on government-frontend. This cherry picks the relevant commits across.

Copy across topic communities

---

app/assets/stylesheets/modules/_page-contents.scss

Add missing empty line between blocks.
app/assets/stylesheets/modules/_page-contents.scss:31 
[W] EmptyLineBetweenBlocks: Rule declaration should be preceded by an empty
line
cc. @AndrewVos.

Fix scss lint offence

---

Gemfile
Gemfile.lock

Use the latest version of the govuk frontend toolkit.
This won't affect any govuk components, e.g. the phase banner or breadcrumb, updating these will require alphagov/static to be updated.
--
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/CHANGELOG.md
- Allow New Transport font stack to be overridden by apps using
`$toolkit-font-stack`
and `$toolkit-font-stack-tabular` (PR #230)
- Fix phase banner alignment (PR #266)
- Add websafe organisation colours
- Split colours into two files with backwards-compatible colours.scss
replacement
- Add GOV.UK lint to lint scss files (PR #260)
- Remove reference to old colour palette (PR #256)
- Fix link to GOV.UK elements - tabular data
- Update DEFRA brand colour to new green (PR #249)
- Pass cohort name to analytics when using …

Update the govuk frontend toolkit to 4.10.0

---

app/presenters/service_manual_guide_presenter.rb
app/views/content_items/service_manual_guide.html.erb
test/integration/service_manual_guide_test.rb

This is being implemented for the point page that uses the service_manual_guide schema.
(The build will be broken until https://github.com/alphagov/govuk-content-schemas/pull/294 makes it's way in)

Display a lede with the guide summary

---

Gemfile
Gemfile.lock
app/assets/stylesheets/modules/_subsections.scss
app/presenters/service_manual_topic_presenter.rb
app/views/content_items/service_manual_topic.html.erb
test/integration/service_manual_guide_test.rb
test/integration/service_manual_topic_test.rb
test/test_helper.rb

We are now allowing the content designers in the publisher to decide whether the accordion is applied or not. There wasn't a clear set of rules that we could define. It seems as though a human needs to decide whether it is collapsed or not.
The default is that the topic sections are expanded. It is more likely that a topic will be collapsed but the downside of a difficult to use topic is more significant than the upside of saving a click in the publisher.

Optionally collapse topics

---

app/controllers/content_items_controller.rb

This filters search results by "/service-manual" when a user searches
from the header inside a service manual content.

Filter search by service-manual content

---

test/controllers/content_items_controller_test.rb

The service manual is enabled now. Also, this would have affected every test that ran after it.

Remove reference to FLAG_ENABLE_SERVICE_MANUAL flag

---

app/presenters/service_manual_guide_presenter.rb
app/views/content_items/service_manual_guide.html.erb
test/controllers/content_items_controller_test.rb
test/integration/government_navigation_test.rb
test/integration/phase_label_test.rb
test/integration/service_manual_guide_test.rb
test/presenters/service_manual_guide_presenter_test.rb

Removes related_discussion which is no longer used and content_owner which has been moved to the links.
Related content schemas PR: https://github.com/alphagov/govuk-content-schemas/pull/313

Remove unused fields from service manual guide

---

app/assets/javascripts/modules/accordion-with-descriptions.js
app/assets/stylesheets/modules/_related-content.scss
app/assets/stylesheets/modules/_subsections.scss

The icon should be 16px in height, set it 50% from the top and with a
negative margin of half its height, so it always sits in the centre.
Also increase the spacing at the bottom of the header, so there isn’t a
“jump” in the position of the icon from plus to minus.
Screenshot before:
Screenshot after:

Adjust the position of the accordion icon

---

app/presenters/service_manual_guide_presenter.rb
test/integration/service_manual_guide_test.rb
test/presenters/service_manual_guide_presenter_test.rb

This field was renamed from 'topics' as it is a reserved field.

Base guide breadcrumb on service_manual_topics field

---

app/assets/javascripts/modules/accordion-with-descriptions.js
spec/javascripts/accordion-with-descriptions-spec.js

When a section is opened - save its ID (with a prefix that identifies it as coming from the GOVUK Service Manual) to local storage with a value of 'Opened' and when it is closed, remove this key from session storage.
When the page loads, check session storage to see if any items have previously been stored and if so, open that section and set the `aria-expanded` attribute of the button to `true`.
cc @thehenster.

Save the state of the accordion using session storage

---

app/views/content_items/service_manual_topic.html.erb

Both Topic and Guide pages should display the page name, followed by -
Digital Service Manual - GOV.UK in the page title.
This was missing from the Topic page, and is added here.

Make page titles consistent

---

app/assets/stylesheets/modules/_subsections.scss

The text will then default to $text-colour, which is #0b0c0c.
Before:
After:

Make accordion description text darker

---

app/presenters/service_manual_service_standard_presenter.rb
app/views/content_items/service_manual_service_standard.html.erb
test/presenters/service_manual_service_standard_presenter_test.rb

This fixes the bug where we sorted alphabetically and 10 came after 1 rather than 2.

Sort service standard points numerically

---

app/presenters/service_manual_guide_presenter.rb
test/presenters/service_manual_guide_presenter_test.rb

Remove ServiceManualGuidePresenter#last_published_time_timestamp

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_page-header.scss

This module can be used on all Service manual page types.
**Service manual - Service Standard page**
```
<div class="page-header">
<h1 class="page-header__title">Digital Service Standard</h1>
<p class="page-header__summary">
The Digital Service Standard is a set of 18 criteria to help government create and run good digital services.
</p>
<p class="page-header__description">
All public facing transactional services must meet the standard. It’s used by departments and the Government Digital Service to check whether a service is good enough for public use.
</p>
</div>
```
**Service manual - Topic page**
```
<div class="page-header">
<h1 class="page-header__title">Agile delivery</h1>
<p class="page-header__summary">
How to work in an agile way: principles, tools and governance.
</p>
</div> …
```

Create a page header module with markup example

---

app/views/content_items/service_manual_guide.html.erb
test/integration/service_manual_guide_test.rb

Until we finalise the design for the feedback footer we might be losing people who would otherwise give feedback. This reapplies the original link on the guide, point and community page.
https://trello.com/c/SPR7fOQG

Put the give feedback link back

---

app/presenters/service_manual_guide_presenter.rb
app/views/content_items/service_manual_guide.html.erb
test/integration/service_manual_guide_test.rb
test/presenters/service_manual_guide_presenter_test.rb

Because we can use the description for the point text this bases whether we display the point text (or summary) on a boolean instead.

Show the description for a point based on a boolean

---

app/views/content_items/service_manual_topic.html.erb
test/integration/service_manual_topic_test.rb

Some topics have been configured with only one section which has neither a name nor a description. From a presentation point of view, we treat those topics as if they are 'sectionless'.
Previously the front-end did not handle that case very well – it still rendered a heading for the section, including a heading and description. This lead to blank h2s which is bad from an accessibility point of view (and also just not a great thing to do)
Now, for topics where there is exactly one section AND that section does not have a title, we skip the header and just output a list of links.

Don't render blank section headings for topics 'without sections'

---

app/presenters/service_manual_guide_presenter.rb
app/views/content_items/service_manual_guide.html.erb
test/integration/service_manual_guide_test.rb
test/presenters/service_manual_guide_presenter_test.rb

https://trello.com/c/7bdchGKi/383-a-guide-s-last-updated-time-updates-each-time-a-topic-is-published
The public_updated_at time is the user facing timestamp to hopefully represent the last major published at time. The updated_at time, which we were using, is updated if a related thing, a topic in this case, updates it.
Move the use of time_ago_in_words into the view and test at the integration level. Testing the rails helper at the unit didn't provide much more confidence than the framework tests give us and this way we can check the timestamp is actually on the page.

Display public_updated_at to user for guides

---

app/assets/stylesheets/modules/_service-standard-point.scss

$gutter = 30px is [already defined in the frontend toolkit](
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/styleshee
ts/_measurements.scss).
Use this, and create `$gutter-tablet` from this.
For a later PR:
It would be better to use em here, as we're using em for top and bottom margins on this module.
This can form part of another piece of work to ensure we're using consistent units.

Use existing vars from the govuk frontend toolkit

---

app/presenters/service_manual_guide_presenter.rb
app/views/content_items/service_manual_guide.html.erb
test/integration/service_manual_guide_test.rb
test/presenters/service_manual_guide_presenter_test.rb
test/support/draft_stack_examples.rb
test/support/govuk_content_schema_examples.rb
test/test_helper.rb

https://trello.com/c/DK1xNwvb
The `public_updated_at` timestamp is not available when previewing the first edition. To avoid a bug we fall back on the `updated_at` field which represents the last time the content item was updated _for any reason_ in the content store. In between a user saving a draft and previewing it, this is most likely going to be the time they saved the draft.
If we ever want to get more precise about this timestamp we should start sending `last_edited_at` to the publishing-api.
I've added a test helper for the draft stack examples which is a lot of trumpeting for deleting a single key from a hash. However, organisation wide I think it's still fairly unknown behaviour so it's a good thing to be a little shouty about.

Timestamp for first draft

---

app/assets/stylesheets/modules/_page-header.scss
app/presenters/service_manual_service_standard_presenter.rb
app/views/content_items/service_manual_service_standard.html.erb
test/integration/service_manual_service_standard_test.rb
test/presenters/service_manual_service_standard_presenter_test.rb

Use link expansion to avoid saving and publishing the service standard every time a point changes.
Publisher PR: https://github.com/alphagov/service-manual-publisher/pull/341

Build the service standard points from the expanded links

---

config/initializers/jasmine_rails.rb
lib/jasmine_rails_spec_runner_controller.rb

This stops the Slimmer middleware being applied when rendering the jasmine runner output in the browser. Without it, the runner output page does not contain a GOV.UK-like page and errors.
After this is merged we can visit http://service-manual-frontend.dev.gov.uk/specs to help debugging.

Skip Slimmer middleware if running Jasmine specs in browser

---

app/views/content_items/service_manual_guide.html.erb
app/views/content_items/service_manual_service_standard.html.erb
app/views/content_items/service_manual_topic.html.erb

The meta description tag is used for the index page of the service manual but none of the sub-pages. This commit adds meta description tags to all pages, the contents of which are set to the description associated with the relevant part of the service manual. This adds descriptions to external search engine results when the pages are re-indexed.
Trello: https://trello.com/c/bbAwFAQ1/108-add-meta-descriptions-to-pages-missing-them

Add meta descriptions

---

Gemfile
Gemfile.lock

Update the Gemfile to use the most recent version of the govuk_frontend_toolkit.
4.18.3 is the change we're interested in, to finish the work on #61. 
This will include the following changes:
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/CHANGELOG
.md
- For smaller screens (<768px) ensure that the
GOVUK.StickAtTopWhenScrolling JS "unsticks" the element which was
previously "stuck" (by removing both the class which sets fixed
positioning and the shim). ([PR
#329](https://github.com/alphagov/govuk_frontend_toolkit/pull/329))
- Remove unnecessary print font fallback that causes regression
downstream ([PR
#328](https://github.com/alphagov/govuk_frontend_toolkit/pull/328))
- Update tooling to use npm script rather than grunt-shell ([PR …

Bump the govuk frontend toolkit to 4.18.3

---

app/presenters/service_manual_service_standard_presenter.rb
app/views/content_items/service_manual_service_standard.html.erb
test/integration/service_manual_service_standard_test.rb
test/presenters/service_manual_service_standard_presenter_test.rb

Include a link to the email alert signup page for the service standard.
Related schemas change: https://github.com/alphagov/govuk-content-schemas/pull/410

Link to service standard email alert signup

---

Gemfile
Gemfile.lock

This release includes two breaking changes:
Removal of external link styles and icons, if you are using the
external-link-* mixins you will need to remove them from your codebase
(PR #293)
Correct spelling of the 'accordion' icon, you will need to check for
the incorrect spelling 'accordian' and update if you are using this
icon (PR #345)
And two minor changes:
Amend GOVUK.StickAtTopWhenScrolling to resize the sticky element and
shim when the .js-sticky-resize class is set (PR #343)
Allow custom options in GOVUK.analytics.trackPageview (#332)

Bump govuk_frontend_toolkit to 5.0.0

---

app/assets/stylesheets/modules/_community-contact.scss
app/assets/stylesheets/modules/_page-header.scss

This fixes #54.
Reduce the spacing under the page context.
Get the "Give feedback on this page" link to line up.
Screenshot before:
Screenshot after:

Fix the alignment of page titles

---

app/assets/stylesheets/mixins/_helpers.scss
app/views/shared/_improve_this_page.html.erb

Before:
After:
This PR fixes the prompt for feedback on the page, it's currently broken for smaller screens.
Clearing the parent wrapper (.js-prompt), fixes this.
Add a .clearfix helper class, use this to extend the contain-floats placeholder from the
govuk_frontend_toolkit.

Fix the improve-this-page prompt for smaller screens

---

app/assets/javascripts/application.js
app/assets/javascripts/modules/highlight-active-section-heading.js
app/assets/stylesheets/modules/_govspeak-wrapper.scss
app/assets/stylesheets/modules/_page-contents.scss
app/views/content_items/service_manual_guide.html.erb
spec/javascripts/highlight-active-section-heading-spec.js

This PR adds a HighlightActiveSectionHeading module.
This will highlight an anchor link in the "Page contents" left hand navigation, when a user has scrolled past the corresponding heading in the main content area. 
This PR also uses the GOVUK.StickAtTopWhenScrolling JS, to "stick" the navigation, once the user has scrolled past the left hand page contents and to "unstick" for smaller viewports.
Steps for this PR:
45ebd8b - duplicating duplicate the GOVUK.StickAtTopWhenScrolling() JS 
and 
a5f8f41 - revert to use govuk/stick-at-top rather than temp/stick-at-top

Highlight anchors in the page contents navigation, on scroll

---

app/views/shared/_improve_this_page.html.erb

The HTML5 validation is provided by the browser and we are not able to style the error messages. This means that the validation experience is inconsistent with other parts of GOV.UK and with any more advanced validation that might happen server side.
There is already server side validation for the description being required, so the simplest fix is just to remove the required attribute and fall back to that.
https://trello.com/c/sIU9cdr1/464-consistent-validation-experience-with-improve-this-page-form

Don’t use HTML5 browser ‘required’ validation

---

app/assets/javascripts/modules/improve-this-page.js
app/views/shared/_improve_this_page.html.erb
spec/javascripts/improve-this-page-spec.js

We need to track what the user is clicking on so we can judge the new feedback form's effectiveness.
The original version of 'Improve this page' tracked the 'Yes' button and the submission of the feedback form. This additionally tracks the 'No' button and the 'Is there anything wrong with this page?' link.

'Improve this page' Google Analyitcs event tracking

---

app/assets/stylesheets/modules/_improve-this-page.scss

This prevents the "improve this page" section from sitting underneath the
page contents and preventing the Yes and No links from being clicked.

Set the improve this page box to be relatively positioned

---

app/helpers/phase_label_helper.rb
app/views/shared/_service_manual_custom_phase_message.html.erb
test/helpers/phase_label_helper_test.rb
test/integration/phase_label_test.rb
test/test_helper.rb

The phase label has a link to fill out a surveymonkey survey. If we add a custom variable with the request path then it'll be possible to see which page the user came from in the surveymonkey analytics.
https://trello.com/c/d8dDWj2i/492-update-survey-monkey-code-on-service-manual-to-return-url-slug-as-custom-dimension

SurveyMonkey custom variable

---

test/integration/improve_this_page_test.rb

Capybara's `#find` does wait, but only for the selector it's provided with. Any chained expectations will not wait. This changes the expectation so we can get rid of the chained stuff.
This is an attempted fix for the intermittent failure on CI.
Here is an example broken build: https://ci.dev.publishing.service.gov.uk/job/govuk_service_manual_frontend_branches/386/console

Use capybara's auto waiting for Improve this page

---

Gemfile
Gemfile.lock
app/controllers/content_items_controller.rb
test/controllers/content_items_controller_test.rb

These days the default behaviour of the gds-api-adapters is to raise a GdsApi::HTTPNotFound if the resource can't be found.
I started out just trying to get rid of the warnings in the test output and realised how far behind gds-api-adapters was, which is where the warning was coming from. Looking at the gds-api-adapters changelog, I don't think it's worth pinning to exact patch versions. It doesn't change that dramatically. This changes the pin to stop it sneakily upgrading to the next major version, but minor and patches are 👌.
https://github.com/alphagov/gds-api-adapters/blob/master/CHANGELOG.md

Upgrade gds-api-adapters to 37.5.1

---

app/assets/javascripts/govuk/current_location.js
app/assets/javascripts/modules/accordion-with-descriptions.js
app/views/content_items/service_manual_topic.html.erb
spec/javascripts/accordion-with-descriptions-spec.js
test/integration/service_manual_topic_test.rb

Allow linking directly to a topic section by adding anchors to all section headings, and modify the accordion Javascript to automatically expand any linked-to section.
The primary use for this is when redirecting from pages in the old manual, which best correspond to a topic section. We don't just want to redirect users to the topic as it may not be obvious why it relates to what they were originally trying to view.

Add anchors to section headings, automatically expand linked to sections

---

spec/javascripts/accordion-with-descriptions-spec.js

Move `accordion.start($element)` inside each individual test so that we don’t need to define two different widely-scoped `beforeEach` callbacks.
As requested by @thehenster in #75

Remove uneccesary `describe` block

---

app/assets/javascripts/modules/accordion-with-descriptions.js
app/views/content_items/service_manual_topic.html.erb
spec/javascripts/accordion-with-descriptions-spec.js

* Rename $subsectionButton and $subsectionHeader to be plural
* Improve readability of Open/Close click event
* Refactor a test to remove a duplicate assertion
* Refactor the tests for the initial state of accordion
Some of the tests now exist within a single test.
We merged some of the test descriptions and comments to make it more readable.

Refactor some accordion tests

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_link-unit.scss
app/presenters/content_item_presenter.rb
app/presenters/service_manual_homepage_presenter.rb
app/presenters/service_manual_service_standard_presenter.rb
app/views/content_items/service_manual_homepage.html.erb
test/integration/homepage_test.rb
test/presenters/service_manual_homepage_presenter_test.rb

This branch is built off of `homepage-intro-and-search`. Once that branch has merged, the target for this branch can be updated to `homepage`.

Include list of topics on homepage [DO NOT MERGE]

---

app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
app/presenters/service_manual_homepage_presenter.rb
app/presenters/service_manual_topic_presenter.rb
test/controllers/content_items_controller_test.rb

This branch is built off of `homepage-intro-and-search`. Once that branch has merged, the target for this branch can be updated to `homepage`.

Remove search on homepage

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_link-unit.scss
app/presenters/content_item_presenter.rb
app/presenters/service_manual_homepage_presenter.rb
app/presenters/service_manual_service_standard_presenter.rb
app/views/content_items/service_manual_homepage.html.erb
test/integration/homepage_test.rb
test/presenters/service_manual_homepage_presenter_test.rb

The previous PR (#55) accidentally had the wrong target (`homepage-intro-and-search`) so it didn't get merged to anywhere useful.
Let's try that again.

Include linked topics on the service manual homepage

---

app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
app/presenters/service_manual_homepage_presenter.rb
app/presenters/service_manual_topic_presenter.rb
test/controllers/content_items_controller_test.rb

This is a revision of PR #56 but targeting master.
We originally merged these homepage-related PRs into a feature branch (`homepage`) and then rebased that branch against master, but it lead to a really weird commit history so we've abandoned that.
So doing this again, but rebasing each branch in turn and targeting master directly.

Remove search on homepage (re-opened PR)

---

app/assets/stylesheets/modules/_link-unit.scss
app/assets/stylesheets/screen.scss
app/presenters/content_item_presenter.rb
app/presenters/service_manual_homepage_presenter.rb
app/presenters/service_manual_service_standard_presenter.rb
app/views/content_items/service_manual_homepage.html.erb
test/integration/homepage_test.rb
test/presenters/service_manual_homepage_presenter_test.rb

This is a revision of PR #82 (originally #55) but targeting master.
We originally merged these homepage-related PRs into a feature branch (`homepage`) and then rebased that branch against master, but it lead to a really weird commit history so we've abandoned that.
So doing this again, but rebasing each branch in turn and targeting master directly.

Include linked topics on the service manual homepage (re-opened PR)

---

app/assets/stylesheets/modules/_panel.scss
app/assets/stylesheets/screen.scss
app/views/content_items/service_manual_homepage.html.erb
test/integration/homepage_test.rb

This is a revision of PR #63 but targeting master.
We originally merged these homepage-related PRs into a feature branch (`homepage`) and then rebased that branch against master, but it lead to a really weird commit history so we've abandoned that.
So doing this again, but rebasing each branch in turn and targeting master directly.

Add homepage links to the standard and communities (re-opened PR)

---

config/routes.rb
test/integration/search_redirect_test.rb

At the moment, requests to /service-manual/search return a 404. These
should really return a 301 round to /search, adding a `filter_manual`
parameter to scope search to the service manual.
This PR adds a new route to handle that particular situation.

Redirect /service-manual/search to /search

---

app/assets/stylesheets/modules/_hero.scss
app/views/content_items/service_manual_homepage.html.erb
test/integration/homepage_test.rb

See individual commits for details

Make the contact link more explicit and obvious

---

app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
app/presenters/homepage_presenter.rb
app/presenters/service_toolkit_presenter.rb
app/views/content_items/service_toolkit.html.erb
app/views/layouts/application.html.erb
test/controllers/content_items_controller_test.rb
test/integration/service_toolkit_test.rb

- Override the header title to 'Service Toolkit'
- Remove the search field
- Use the 'old style' feedback form for the Service Toolkit
- Remove the footer links in both the Service Toolkit and the Service Manual

Header and footer for Service Toolkit

---

app/assets/stylesheets/modules/_change-history.scss
app/presenters/guide_presenter.rb
app/views/shared/_change_history.html.erb
test/integration/guide_test.rb
test/presenters/guide_presenter_test.rb

The ‘reason for change’ often duplicates the change note so is being removed to prevent duplication and confusion.
There will be follow up work to remove the reason for change from the content schemas and the Service Manual Publisher.

Do not display reason for change in change history

---

app/views/content_items/service_toolkit.html.erb

We want to be able to ‘deep link’ directly to e.g. the collection of components. Providing an ID allows us to do this using the hash part of the URL.
https://trello.com/c/1e6QTqAQ/558-add-anchors-to-service-toolkit

Add anchors to collections on toolkit page

---

app/assets/stylesheets/modules/_service-standard-point.scss

Removing the top margin for the first service standard point vertical aligns it with the notifications sidebar
**Before:**
**After:**

Fix vertical alignment

---

app/assets/javascripts/modules/accordion-with-descriptions.js
spec/javascripts/accordion-with-descriptions-spec.js

https://trello.com/c/u7d0Smkt
I've tried to move some of the shared behaviour into a `SubsectionView` object. It should be possible to reuse the behaviour in `SubsectionView` in the `bindToggleOpenCloseAllButton()` function which would be a decent win.
Long term I think this could benefit from an `Accordion` object too, where the jQuery selectors are defined once and reused.

Integrated accordion tracking

---

Jenkinsfile

This adds support for running schema tests in govuk-content-schemas.
For more information, see [here](https://github.gds/gds/opsmanual/pull/862/files?short_path=db37eb8#diff-db37eb8a3f2b8b7408aa69b7a0435c61).

Add schema test support to Jenkinsfile

---

test/integration/improve_this_page_test.rb

This test is extremely unreliable, both on CI and locally.
I've tried various things in an attempt to improve its reliability:
- Changing the selector (to `.js-feedback-form.js-hidden`)
- Adding a `sleep`
- Setting a high `wait` on the `has_css?` call
- Removing the first `assert`
None of these solutions fix the build reliably. Adding a `sleep` or
increasing the `wait` time seems to make it occur less, but means that
the build can take huge amounts of time to complete if the element isn't
found for whatever reason (which appears to be the root cause of the
issue).
Changing the underlying Capybara driver to capybara-webkit _does_
increase reliability, however it's difficult to run on CI and massively
increases the complexity of running the test suite.
To that end – the simplest course of …

Remove flaky "improve this page" test

---

app/assets/javascripts/modules/accordion-with-descriptions.js
spec/javascripts/accordion-with-descriptions-spec.js

Spotted while porting the accordion analytics tracking to collections.
The Jasmine tests were manipulating the session state in the test code, which meant that they were not fully testing that the application code.
This fixes the problem by removing all state changes in the tests except for resetting the session storage after each test.
To support this, some jQuery selectors have also been updated from `$('foo')` to `$element.find('foo')`. This doesn't change the behaviour in the browse, but it makes the code more consistent (since `find` was already being used elsewhere) and it means that the selector is correctly applied to the HTML fixture in the tests.

Fix JavaScript tests of accordion session storage

---

app/assets/javascripts/modules/improve-this-page.js
app/assets/stylesheets/modules/_improve-this-page.scss
app/views/shared/_improve_this_page.html.erb
spec/javascripts/improve-this-page-spec.js

At the moment, if I'm shown the feedback form in the improve this page
component, there's no way to close it. This is apparently rather
annoying, particularly on smaller viewports, so this adds a "Close" link
allowing users to close it.

Allow "improve this page" form to be closed

---

app/presenters/service_standard_presenter.rb
app/views/content_items/service_standard.html.erb
test/presenters/service_standard_presenter_test.rb

This adds a new attribute on the `ServiceStandardPresenter` and
associated bit of UI to allow users to download a PDF of the service
standard for sticking on a wall.
Dependent on alphagov/govuk-content-schemas#524.

Add option to download service standard poster

---

README.md
app/controllers/content_items_controller.rb

Users will often visit the root of an application when they first start it, to make sure it is working. At the minute, we throw an exception if you try to do this. This is intentional – applications should serve on the routes as they would appear on GOV.UK, so the service manual shouldn’t do anything for `/` – it’s homepage is at `/service-manual`.
However, the exception we throw (No support for format special_route) does not make this obvious. This handles the root as a special case, tries to makes the general error message more useful as well, and adds some documentation to the README.

Raise better errors for unsupported formats

---

app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
test/presenters/content_item_presenter_test.rb

The format field has been deprecated and is now being removed, so we should use `document_type` instead.
Related to alphagov/govuk-content-schemas#598

Use document type instead of format

---

app/assets/stylesheets/hacks/_full-width.scss

For the service toolkit, we override the wrapper to make it full width to allow for the full width masthead. This means that it doesn’t center the feedback form and its toggle as it does on other pages on GOV.UK.
Sadly this means we need to add more hacks to explicitly center the feedback form and its toggle when this full width override is in place.

Fix alignment of feedback form on Service Toolkit

---

Jenkinsfile

For: https://trello.com/c/QtpGwa2A/288-improve-feedback-on-github-for-changes-to-govuk-content-schemas
Using the standard buildProject defined in our groovy library means we get
consistent behaviour across all applications, and allows us to improve our
CI process in one place.
The only difference between our custom Jenkinsfile and buildProject is
that we need to use `overrideTestTask` to run `rake test` followed by
`rake spec:javascript`.  Left to its own devices `buildProject` would
run `rake default` which in our case would run lint again, and that's
already run by the Jenkinsfile in a previous stage so we don't want to
double up our effort.

Use standard buildProject in Jenkinsfile

---

Dockerfile

Our `.ruby-version` is 2.4.2 so we need to use the `ruby:2.4.2` base image
for our `Dockerfile`.

Make sure the `Dockerfile` is in sync with `.ruby-version`

---

app/assets/javascripts/application.js
app/assets/javascripts/start-modules.js
app/views/layouts/application.html.erb
config/initializers/assets.rb

For: https://trello.com/c/AK6V1hHg/103-sort-out-govuktoolkit-use-in-frontend-apps-to-avoid-object-object-in-ga
When the application is deployed we get the govuk_toolkit js files from
static, if we also include them in our own JS bundle we:
1. make users effectively download the same code twice
2. run the risk of delivering two different versions of the code and
causing errors in how things interact
3. run the risk of delivering two versions of the code that interact
strangely because they end up redefininig things and cause things
like type-checks to fail
Of course, if we rely on static to deliver this JS we won't have it in
test environments and so JS that relies on it can fail.  To get around
this problem we can include a separate JS file that does include the
bits we need only in …

Be more selective about govuk_toolkit requires in application.js

---

Gemfile.lock

The Ruby version is out of sync with the Gemfile, causing Heroku deploys to fail.

Fix Heroku review apps

---

app/views/content_items/guide.html.erb
app/views/layouts/application.html.erb

Adding this component will add schema.org metadata, Facebook/OpenGraph tags, Twitter card tags and a canonical tag for content pages.
https://trello.com/c/gKHoUGuA

Add machine readable metadata

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/views/content_items/guide.html.erb
test/controllers/content_items_controller_test.rb
test/test_helper.rb

Because we're now no longer using components from Static, we can upgrade slimmer and remove usage of Slimmer::GovukComponents.
https://trello.com/c/ZMVwIyj5

Use govspeak component from gem

---

app/views/layouts/application.html.erb

There should only be one H1 on the page, and the H1 should be the title of the page rather than the title of the product. For that reason, this replaces the H1 in the header with a span.

Remove H1 from title

---

app/views/shared/_custom_phase_message.html.erb

The Service Manual has a custom phase banner. It tells users content is new when it isn't. This PR: 
+ changes the banner wording so it doesn't say the content is new
+ updates the phase banner test so it won't fail because of the wording change
**Please note I'm a content designer and have a very limited idea of what I'm doing.**
On "guides", the phase banner says "This is new guidance. Complete our quick 5-question survey to help us improve it."
A lot of the guidance isn't new - it's been around for over a year in some cases. The age of the guidance is shown to users under the guide's top heading so the contrast is rather jarring. 
For example: https://www.gov.uk/service-manual/design/naming-your-service.
The homepage version of the banner doesn't have the 'This is new' phrase, so I've …

Change beta phase banner content

---

Gemfile

As wraith depends unnecessarily on an older version of the
chromedriver-helper gem, installing this gem causes issues with
chromedriver working correctly.
Moving this to the development group prevents wraith being
unnecessarily installed, which should work around this issue.

Move wraith to the development group

---

app/views/shared/_improve_this_page.html.erb
spec/javascripts/improve-this-page-spec.js

The "How should we improve this page?" currently sends the user agent of the request.
Like https://github.com/alphagov/govuk_publishing_components/pull/699, this is wrong because the page will be cached, so that any subsequent page requests will return the same HTML with the same form fields - and the previous request's user agent.
Because this feature has been broken for a number of years, we're removing it instead of fixing it. We think the reason the user agent was included in the first place was taken from GOV.UK. We've found no good reason to collect this information.

Don't send User Agent in contact form

---

app/assets/javascripts/application.js

Scripts in govuk_publishing_components contain not only component-related scripts, but also polyfills and accessibility shims that should be included in every application.

Load all scripts from govuk_publishing_components

---

app/views/content_items/guide.html.erb

- toggle js module seems to be initialised twice, fix is to use the gem-toggle (copy code) in the components gem instead

Fix 'show all updates' link

---

test/integration/guide_test.rb

When `travel_to("2015-10-10")` is called from a test environment in British Summer Time then Time.now is reported as `2015-10-10 00:00:00 +0100` but the tests assume it’ll be `2015-10-10 00:00:00 +0000`.
This means that the time reported in '.metadata' is reported as 'about 15 hours ago' which means the test fails.
I assume that this isn’t being seen on CI because CI lives in UTC(?).

Fix failing test when run in BST

---

app/views/content_items/homepage.html.erb
app/views/content_items/service_standard.html.erb
test/integration/homepage_test.rb
test/integration/service_standard_test.rb
test/integration/service_toolkit_test.rb
test/presenters/guide_presenter_test.rb
test/presenters/service_standard_presenter_test.rb

**DO NOT MERGE WITHOUT CONFIRMING WITH SERVICE MANUAL TEAM** – the Service Standard's name is not changing yet.
Related:
- https://github.com/alphagov/service-manual-publisher/pull/530
- https://github.com/alphagov/govuk-content-schemas/pull/812

[DO NOT MERGE] Rename service standard

---

app/assets/javascripts/modules/improve-this-page.js
app/assets/stylesheets/modules/_improve-this-page.scss

Screenreaders lose focus at the point that the feedback form is closed,
this resets the focus to where they came from and ensures correct
contrast on the focused link.
This brings the feedback section of the page in line with the version used throughout most of GOV.Uk via the govuk_publishing_components gem

When feedback form is closed refocus on the control that opened it

---

app/views/content_items/guide.html.erb

Add correct text to updates toggle on expanded

---

app.json
app/controllers/application_controller.rb

Taken from https://github.com/alphagov/government-frontend/pull/1484 . The username and password have already been defined within Heroku.

Add basic auth to Heroku apps

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/start-modules.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_sticky.scss
app/views/content_items/guide.html.erb
app/views/layouts/application.html.erb
config/initializers/assets.rb

Remove govuk-frontend-toolkit from service-manual-frontend.
This involves only one noticeable change for users - on [guide pages](https://www.gov.uk/service-manual/helping-people-to-use-your-service/making-your-service-accessible-an-introduction) a script from toolkit was being used to simulate `position: sticky`. This has been removed (well, not removed, but not called from toolkit anymore) and replaced with actual `position: sticky`. 
Sticky is supported in all major browsers apart from IE, but the only difference is that the menu won't scroll with the page. Consensus among the FE devs is that it's not worth the effort of a polyfill (also I tried and there are several problems that make the code hacky, so best avoided).
Goodnight toolkit, well, it's time to go...
No visual changes other …

Remove frontend toolkit from service manual frontend

---

app/assets/stylesheets/modules/_change-history.scss
app/views/shared/_change_history.html.erb

This change allows change notes to have multiple lines. It also strips any leading or trailing white space from change notes.
Currently change notes are displayed on a single line, which can make certain larger changes hard to read. 
[trello](https://trello.com/c/rdNti5Hh/1670-5-investigate-and-fix-allowing-line-breaks-in-change-notes)
Before:
After:

Allow new lines to show in change notes

---

app/assets/stylesheets/application.scss

The legacy palette flag (`$govuk-use-legacy-palette`) is set to false to turn on the new colours.
Part of the process to make GOV.UK more accessible - card is https://trello.com/c/Dd49EiEv/122-switch-to-new-colours-in-service-manual-frontend
Oh so many. 
Any yellow and blue should change from:
to:
* https://govuk-service-manual-fr-pr-616.herokuapp.com/service-manual/
* https://govuk-service-manual-fr-pr-616.herokuapp.com/service-manual/helping-people-to-use-your-service
* https://govuk-service-manual-fr-pr-616.herokuapp.com/service-manual/design
* https://govuk-service-manual-fr-pr-616.herokuapp.com/service-manual/service-assessments
* https://govuk-service-manual-fr-pr-616.herokuapp.com/service-manual/service-standard
* https://govuk-service-manual-fr-pr-616.herokuapp.com/service-manual/s …

Turn off legacy colour palette to update to new colours

---

Gemfile
Gemfile.lock

Remove dependency on `govuk_elements_rails`
Because it is not being used
None expected 🤞 
* https://govuk-service-manual-fr-pr-623.herokuapp.com/service-manual/
* https://govuk-service-manual-fr-pr-623.herokuapp.com/service-manual/helping-people-to-use-your-service
* https://govuk-service-manual-fr-pr-623.herokuapp.com/service-manual/design
* https://govuk-service-manual-fr-pr-623.herokuapp.com/service-manual/service-assessments
* https://govuk-service-manual-fr-pr-623.herokuapp.com/service-manual/service-standard
* https://govuk-service-manual-fr-pr-623.herokuapp.com/service-manual/service-standard/point-1-understand-user-needs
* https://govuk-service-manual-fr-pr-623.herokuapp.com/service-manual/communities
* https://govuk-service-manual-fr-pr-623.herokuapp.com/service-manual/communities …

Remove unused dependency on govuk_elements_rails

---

.github/PULL_REQUEST_TEMPLATE.md

Replace heroku review app links with just base paths.
We are using the new heroku review apps, which don't have fixed URLs based on PR number. However, we don't want to remove the links entirely as they are a good reminder of pages to check which can otherwise be missed.

Replace heroku links with paths

---

spec/javascripts/highlight-active-section-heading-spec.js

Update a spec file that uses old `grid-row` classes.
grid-row styles are deprecated in favour of govuk-frontend.
No change.

Update spec test

---

app/presenters/guide_presenter.rb
app/presenters/service_standard_presenter.rb
app/presenters/topic_presenter.rb
test/presenters/guide_presenter_test.rb
test/presenters/service_standard_presenter_test.rb
test/presenters/topic_presenter_test.rb

Updated Service manual breadcrumb to not display the last item without a url. This is as per the updated breadcrumb design where the last item should be current pages parent
For reference:
https://docs.google.com/document/d/1OFG1Ln6VeCR_bc0qmUtRwMJU62Ljw4F3HO6hq2yloXk
Trello card:
https://trello.com/c/VorvrMfy/39-change-it-so-service-manual-doesnt-use-breadcrumb-for-current-page-option
- removed guide item with no url
- remove topic title with no url
- removed topic breadcrumb with no url
- updated tests to remove no url last item
Consistent breadcrumb functionality to show parent as the last item and not the current documents title

Change Service Manual to not use 'breadcrumb for current page' option

---

Gemfile
Gemfile.lock
app/views/content_items/guide.html.erb
app/views/content_items/service_standard.html.erb
app/views/content_items/topic.html.erb
test/integration/guide_test.rb

Add `collapse_on_mobile` flag to breadcrumbs
We want breadcrumbs to be consistent across GOVUK
* https://govuk-servic-collapse-b-1rjnmt.herokuapp.com/service-manual/
* https://govuk-servic-collapse-b-1rjnmt.herokuapp.com/service-manual/helping-people-to-use-your-service
* https://govuk-servic-collapse-b-1rjnmt.herokuapp.com/service-manual/design
* https://govuk-servic-collapse-b-1rjnmt.herokuapp.com/service-manual/service-assessments
* https://govuk-servic-collapse-b-1rjnmt.herokuapp.com/service-manual/service-standard
* https://govuk-servic-collapse-b-1rjnmt.herokuapp.com/service-manual/service-standard/point-1-understand-user-needs
* https://govuk-servic-collapse-b-1rjnmt.herokuapp.com/service-manual/communities
* https://govuk-servic-collapse-b-1rjnmt.herokuapp.com/service-manual/commun …

Collapse breadcrumbs on mobile

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/content_items_controller.rb
test/integration/guide_test.rb
test/integration/phase_label_test.rb
test/integration/service_toolkit_test.rb
test/integration/topic_test.rb
test/presenters/guide_presenter_test.rb
test/presenters/topic_presenter/topic_group_test.rb

- See commits for more detail.
- Done as part of the GOV.UK Developer Tooling working group: https://trello.com/c/pR7GEFfU/128-make-all-current-govuk-repos-use-rubocop-govuk-instead-of-govuk-lint

Use `rubocop-govuk` instead of `govuk-lint`

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/print.scss

Update service-manual-frontend to import the sass and Javascript for only the components it is using, instead of all components, as [documented here](https://github.com/alphagov/govuk_publishing_components/blob/master/docs/install-and-use.md#import-sass-for-individual-components) and [here](https://github.com/alphagov/govuk_publishing_components/blob/master/docs/install-and-use.md#import-javascript-for-individual-components).
Before:
CSS: **916 KB** 
JS: **796 KB** 
After:
CSS: **441 KB**
JS: **184 KB** 
Trello card: https://trello.com/c/GWttlBxs/228-upgrade-applications-to-use-individual-component-sass

Use individual component Sass and JS

---

app/presenters/service_standard_presenter.rb
app/presenters/topic_presenter.rb
app/views/content_items/service_standard.html.erb
app/views/content_items/topic.html.erb
test/contracts/govuk_content_schemas_test.rb
test/controllers/content_items_controller_test.rb
test/integration/guide_test.rb
test/integration/service_standard_test.rb
test/integration/topic_test.rb
test/presenters/service_standard_presenter_test.rb
test/presenters/topic_presenter_test.rb
test/support/govuk_content_schema_examples.rb
test/test_helper.rb

https://trello.com/c/KNWv9Dgx/258-deprecate-and-remove-legacy-email-signup-pages
Depends on: https://github.com/alphagov/email-alert-frontend/pull/806
Previously we relied on each topic (and the service standard) having
an associated '/email-signup' content item. The matching criteria are
the topic itself, with a restriction on the document type [1]. The
additional document type restriction turns out to be redundant, since
service manual guides are the only document type linked to service
manual topics (and similarly for the service standard). This repoints
the email signup links to the generic page on Email Alert Frontend,
which supports signups to a given content item.
[1]: https://github.com/alphagov/service-manual-publisher/blob/master/app/presenters/topic_email_alert_signup_presenter. …

Repoint email signups to generic API

---

config/application.rb
config/environments/development.rb
config/environments/production.rb

Trello: https://trello.com/c/oNEtjIVp/99-serve-static-assets-from-www-hostname
This allows asset host to be set by ASSET_HOST env var. This is in
preparation for the assets of this app changing hostname from
assets.publishing.service.gov.uk to www.gov.uk.
As part of this change the path to assets is changed to
/assets/service-manual-frontend
The expectation is that this env var will only be set in dev
environments when proxying isn't set up for router.
This also removes some redundant slimmer config that sets the default.

Switch asset host env var for change of asset host

---

app/views/layouts/application.html.erb

Fixes the layout of the feedback component being full screen width, it should be the width of the page. This is due to a change in the component where we removed the width constraint, preferring to let applications handle it.
Before:
After:
Also fixes it on mobile:
* /service-manual/
* /service-manual/helping-people-to-use-your-service
* /service-manual/design
* /service-manual/service-assessments
* /service-manual/service-standard
* /service-manual/service-standard/point-1-understand-user-needs
* /service-manual/communities
* /service-manual/communities/accessibility-community

Fix feedback layout

---

.github/PULL_REQUEST_TEMPLATE.md

Very small change, adds a missing space into the github PR template so the list formats properly.
It wasn't showing one of the list items correctly when rendered.

Add missing space to correct formatting

---

Gemfile
Gemfile.lock
spec/javascripts/support/jasmine_helper.rb
spec/javascripts/support/jasmine_selenium_runner.yml
test/test_helper.rb

This adds the govuk_test gem which provides Capybara configuration and other test utilities (notably Brakeman). It then configures Jasmine Selenium Runner to use this, which will allow these tests to succeed once https://github.com/alphagov/govuk-docker/pull/394 is merged.

Install govuk_test and configure Jasmine to use it

---

Rakefile
lib/tasks/testing.rake

Trello: https://trello.com/c/5Gob6WUL/147-for-everyone-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks
We had expected that all apps were linting with the default rake task
and removed the linting step from the Jenkins library [1]. However it
seems this app was missed.
The rails test task always seem to run last when part of the default
group despite any ordering. I've tried to make this at least appear
explicit by defining jasmine:ci before test, even though this is
different for how GOV.UK normally applies it.
[1]: https://github.com/alphagov/govuk-jenkinslib/pull/74

Lint as part of the default rake task

---

app/presenters/service_standard_presenter.rb
app/presenters/topic_presenter.rb
test/integration/service_standard_test.rb
test/integration/topic_test.rb
test/presenters/service_standard_presenter_test.rb
test/presenters/topic_presenter_test.rb

https://trello.com/c/oYRFCtBm/668-iterate-error-content-and-behaviour-for-new-signup-workflow
This is preferred for the signup API [1] [2].
[1]: https://github.com/alphagov/email-alert-frontend/pull/971
[2]: https://github.com/alphagov/email-alert-frontend/blob/5f132d43d0dfc378248b228525e1393a495931cb/app/controllers/content_item_signups_controller.rb#L43

Switch to use "link" query param for email signups

---

app/views/content_items/guide.html.erb
app/views/content_items/homepage.html.erb
app/views/content_items/service_standard.html.erb
app/views/content_items/service_toolkit.html.erb
app/views/content_items/topic.html.erb
app/views/shared/_email_signup.html.erb
test/integration/service_standard_test.rb

Update several instances of custom markup or markup directly from the design system.
This is part of an ongoing effort in the govuk accessibility team to use components in as many places as possible, ensuring that we can more easily deploy bugfixes and accessibility updates across our apps and avoid blind spots in our code coverage.
No visual changes.
[Card](https://trello.com/c/yB2tjxwt/564-update-service-manual-frontend-to-use-components)

Make use of gem components where possible

---

app/helpers/application_helper.rb
app/presenters/content_item_presenter.rb
app/presenters/homepage_presenter.rb
app/presenters/service_toolkit_presenter.rb
app/presenters/topic_presenter.rb
test/controllers/content_items_controller_test.rb
test/integration/topic_test.rb
test/presenters/topic_presenter_test.rb

Clean up and adds some missing tests for Service Manual Frontend in preparation for enabling continuous deployment.
Main features of the app are tested, the two Javascript modules are both tested and the ruby test coverage is now near 100%:
```
Coverage report generated for Minitest, Unit Tests to /govuk/service-manual-frontend/coverage. 248 / 249 LOC (99.6%) covered. 
```
Trello:
https://trello.com/c/zu7IYR6C/2385-enable-continuous-deployment-for-service-manual-frontend

Add missing tests

---

app/views/content_items/guide.html.erb
test/integration/guide_test.rb

Removal of timestamp at the top of each guidance page: Taking out the ‘Last updated’ information below the guidance title –while the timestamp information remains at the bottom of each guidance page.
User research has shown that users of the Service Manual are irritated and trusting guidance less if it has an old timestamp. It distracts from useful and potentially recently reviewed but unchanged guidance. The timestamp information remains available to users at the bottom of each page. Further details can be found in this [user research findings document](https://docs.google.com/presentation/d/1xYaMannwtE-KlLb37RZc …

Remove top timestamp

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_typography.scss
app/views/content_items/homepage.html.erb

Set `$govuk-new-link-styles: true` in `application.scss` to enable the new link styles from the Design System.
The new DS link styles are being rolled out across GOVUK.
We've already applied the new styles to the individual components in the component gem. The next step is to enable them on the frontend applications themselves.
This switches `service-manual-frontend` over to the new styles by setting the `govuk-new-link-styles` flag to `true` in the
`application.scss` file. 
The types of pages rendered by this application are primarily content heavy pages. There are no app-level components to speak of, which makes transitioning to the new link styles a fairly straightforward process. I've tested this on the [Example pages rendered by …

Switch to new Design System link styles

---

app/views/layouts/application.html.erb

Change markup for header sent to Slimmer that gets injected into template. This is part of fixing the header.
[Trello card](https://trello.com/c/7xbAX1Uk/711-bug-fix-service-manual-header)
* https://github.com/alphagov/govuk_publishing_components/pull/2521
* https://github.com/alphagov/static/pull/2672
Since the change to new layout header, the markup became out of date and wasn't applying correct styles.

Fix markup for page titles

---

app/assets/javascripts/modules/highlight-active-section-heading.js
spec/javascripts/highlight-active-section-heading-spec.js

Removes jQuery from the only script in this application that uses it, `highlight-active-section-heading.js`.
This script highlights the menu item for the section of the page that is currently in view, on pages like https://www.gov.uk/service-manual/helping-people-to-use-your-service/making-your-service-accessible-an-introduction
There's a bit of clumsiness in this script where 3 functions do nothing but return the value of a new function, `getElementPosition`. I wanted to consolidate them all into one function, but the test depends on overriding these functions in order to pass. This isn't ideal, but any changes …

Remove jQuery from highlight active section

---

app/controllers/content_items_controller.rb

Change the `static` layout which is used for both [The Service Manual](https://www.gov.uk/service-manual) and the [Service Toolkit](https://www.gov.uk/service-toolkit) pages.
Both pages will now use a new `static` template - `gem_layout_full_width_no_footer_navigation`. Added here: https://github.com/alphagov/static/pull/2754.
All other pages use `gem_layout_no_footer_navigation`.
To fix layout issues:
- There's a blue bar (from the footer) that's showing up in the header
| Before | After |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/87758239/165111985-bbf0d56b-c2e6-4f5b-9031-ff7b09667919.png" width="360"> | <img src="https://user-images.githubusercontent.com/87758239/165112167-c76103e4-6669-49fd-98ef-5a0d079dd908.png" width="360"> |
| <img …

Change layout to fix header issue

---

Dockerfile

The mv to /tmp causes issues at container runtime
https://trello.com/c/Jef1t4xU/903-fix-app-permission-errors-due-to-nonroot

Have to change from mv to cp

---

.github/workflows/deploy.yaml

Add an additional environment input to the workflow dispatch in deploy.yaml with a choice input type to allow the user to select the desired environment. 
I am updating the inputs passed to the GHA workflow when run manually to allow the user to pass in the environment they want to deploy to from a dropdown. This will allow for a more seamless rollback of changes to environments other than integration.
https://trello.com/c/tUyJa4cb/923-extend-gha-to-deploy-to-specific-environment

Adding updates to the required inputs for GHA deploy workflow

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/print.scss

- Remove stylesheets and JavaScript imports that are included in Static
- Update component JavaScript imports: removed button and added metadata
Reduces `application.css` from 114.56 kB to 86.75 kB uncompressed.
Reduces `application.js` from 66.31 kB to 50.38 kB uncompressed.
If CSS or JavaScript is shared across multiple rendering applications, then that code should be included in `static`'s CSS and JavaScript files. They can then be cached across a user's entire journey rather than just across the pages rendered by a single application.
The button component isn't being used by this application, so the button component JavaScript can be removed with no ill effect.
The metadata component's JavaScript wasn't being imported. Thanks to progressive enhancement this was okay and didn't pose a …

Tidy up stylesheet and JavaScript imports

---

app/presenters/topic_presenter.rb
app/views/content_items/topic.html.erb
test/presenters/topic_presenter_test.rb

We are currently working to complete the implementation of GA4 tracking on all accordions, across all frontend apps.
This PR adds tracking to the accordions on the following page:
Example URL(s):
- https://www.gov.uk/service-manual/agile-delivery
- https://www.gov.uk/service-manual/helping-people-to-use-your-service
- https://www.gov.uk/service-manual/user-research
- https://www.gov.uk/service-manual/technology
[Trello](https://trello.com/c/0gjuZZxe/344-complete-the-implementation-of-ga4-accordions-on-all-frontend-apps)
None

Add GA4 accordion tracking

---

app/views/content_items/topic.html.erb

Remove the title from the GA4 tracking on accordions
The title is automatically supplied by the tracking script, so passing it in directly is no longer required.
None
[Trello](https://trello.com/c/0gjuZZxe/344-complete-the-implementation-of-ga4-accordions-on-all-frontend-apps)

Remove the show all title from accordion GA4 tracking

---

app/presenters/topic_presenter.rb
app/views/content_items/topic.html.erb
test/presenters/topic_presenter_test.rb

Add the `module` to the `data_attributes` hash within the accordion component.
The `Show/hide all sections` part of the accordion on the manuals pages is not being tracked and the `dataLayer` push is not firing.
None 
[Trello](https://trello.com/c/PiCNfSZq/374-datalayer-push-not-functioning-on-some-show-hide-all-sections-accordion-interactions)

Accordion show/hide all sections not working on topic pages

---

Gemfile
Gemfile.lock
test/integration/topic_test.rb
test/presenters/guide_presenter_test.rb
test/presenters/homepage_presenter_test.rb
test/presenters/service_standard_presenter_test.rb
test/presenters/topic_presenter_test.rb
test/support/govuk_content_schema_examples.rb

Remove the obsolete govuk-content-schema-test-helpers gem and replace with govuk_schemas.
Old gem is obsolete and archived, we should not be using: https://trello.com/c/b9PRFqgU/231-applications-use-govuk-content-schema-test-helpers-which-is-an-archived-gem
No visual changes (only affects test suite).

Replace obsolete govuk-content-schema-test-helpers with govuk-schemas.

---

app/views/content_items/topic.html.erb

**NOT TO BE MERGED unless also including the [new version of the components gem](https://github.com/alphagov/govuk_publishing_components/pull/3091) that includes the changes detailed below**
- ahead of a change to how tracking and accordion tracking works, update accordions to have the simpler `ga4_tracking:true` option instead of passing multiple data attributes
Page where the accordion appears: https://www.gov.uk/service-manual/helping-people-to-use-your-service
We've been changing how tracking works a little, specifically in https://github.com/alphagov/govuk_publishing_components/pull/3082 and this PR updates …

Update GA4 accordion tracking

---

.github/workflows/deploy.yml

This adds default values for inputs used in the deploy workflow, when not trigger via workflow_dispatch trigger.

Add defaults for inputs on deploy workflow
