alphagov/service-manual-frontend

startup.sh

This didn't get updated when forked from government-frontend.

Update port in startup.sh

---

app/views/content_items/service_manual_guide.html.erb
app/views/shared/_service_manual_custom_phase_message.html.erb
test/integration/phase_label_test.rb

Survey monkey and feedback links

---

app/assets/javascripts/modules/accordion-with-descriptions.js

- Get the h1
- Replace spaces with underscores
- Return a unique prefix for each subsection content area
cc @thehenster.

Create two new functions to simplify creating a prefix

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_service-standard-point.scss
app/assets/stylesheets/modules/_service-standard.scss
app/presenters/service_manual_guide_presenter.rb
app/presenters/service_manual_service_standard_presenter.rb
app/views/content_items/service_manual_guide.html.erb
app/views/content_items/service_manual_service_standard.html.erb
test/integration/service_manual_service_standard_test.rb
test/presenters/service_manual_guide_presenter_test.rb
test/presenters/service_manual_service_standard_presenter_test.rb

We are replacing https://www.gov.uk/service-manual/digital-by-default
https://trello.com/c/oDSuK5ay

Service standard

---

README.md

The Service manual frontend appplication is using the BEM methodology, with  modifications.
Add information about this to the README.
cc. @36degrees.

Add a section on the use of BEM to the README

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_lede-text.scss
app/assets/stylesheets/modules/_page-header.scss
app/assets/stylesheets/modules/_service-standard.scss
app/views/content_items/service_manual_guide.html.erb
app/views/content_items/service_manual_service_standard.html.erb
app/views/content_items/service_manual_topic.html.erb
test/integration/service_manual_guide_test.rb

Use new page header module

---

app/assets/stylesheets/modules/_service-standard-point.scss
app/presenters/service_manual_service_standard_presenter.rb
app/views/content_items/service_manual_service_standard.html.erb

Align point titles, move point numbers into margin

---

app/assets/stylesheets/modules/_main-service-manual.scss
app/presenters/service_manual_homepage_presenter.rb
app/views/content_items/service_manual_guide.html.erb
app/views/content_items/service_manual_homepage.html.erb
app/views/content_items/service_manual_service_standard.html.erb
app/views/content_items/service_manual_topic.html.erb
app/views/layouts/application.html.erb
app/views/shared/_service_manual_custom_phase_message_homepage.html.erb
test/integration/homepage_test.rb

See individual commits for details.

Homepage finishing touches

---

app/assets/stylesheets/modules/_collection.scss
app/assets/stylesheets/modules/_hero.scss
app/assets/stylesheets/screen.scss
app/presenters/content_item_presenter.rb
app/presenters/guide_presenter.rb
app/presenters/service_toolkit_presenter.rb
app/views/content_items/service_toolkit.html.erb
test/integration/service_toolkit_test.rb

https://trello.com/c/iJi4IFtI/545-main-content-on-page

Display hero and links on Service Toolkit

---

app/assets/stylesheets/_common.scss
app/assets/stylesheets/hacks/_full-width.scss
app/assets/stylesheets/hacks/_header-tweaks.scss
app/assets/stylesheets/modules/_hero.scss
app/assets/stylesheets/screen.scss
app/controllers/content_items_controller.rb
app/presenters/content_item_presenter.rb
app/views/content_items/homepage.html.erb
app/views/content_items/service_toolkit.html.erb
app/views/layouts/application.html.erb
app/views/shared/_improve_this_page.html.erb
test/presenters/content_item_presenter_test.rb
test/presenters/guide_presenter_test.rb

https://trello.com/c/30jayY3T/554-new-blue-banner-style

Full width service manual and toolkit heros

---

Jenkinsfile

Add JavaScript test step to the Jenkinsfile.

Run Jasmine tests in CI build

---

app/views/shared/_custom_phase_message.html.erb
app/views/shared/_custom_phase_message_homepage.html.erb
test/integration/phase_label_test.rb
test/support/govuk_content_schema_examples.rb

https://trello.com/c/9rHHUmdX/578-stop-surveymonkey-ending-on-blank-screen

Open survey links in a new window

---

app/assets/javascripts/modules/improve-this-page.js
app/assets/stylesheets/modules/_improve-this-page.scss
spec/javascripts/improve-this-page-spec.js

https://trello.com/c/Ai7ATgqK/580-improve-feedback-form

Preserve feedback form on error

---

app/helpers/phase_label_helper.rb
app/views/shared/_custom_phase_message.html.erb
app/views/shared/_custom_phase_message_homepage.html.erb
test/helpers/phase_label_helper_test.rb
test/integration/phase_label_test.rb

This needs testing in the review app before merging.

Update survey url

---

app/views/content_items/guide.html.erb
app/views/content_items/service_standard.html.erb
app/views/content_items/topic.html.erb
test/integration/guide_test.rb

This has moved from Static.
https://trello.com/c/XLuzv0pB

Use breadcrumb component from gem

---

app/helpers/phase_label_helper.rb
test/integration/phase_label_test.rb

Use phase banner from gem

---

.rubocop.yml
app/controllers/content_items_controller.rb
app/presenters/guide_presenter.rb
test/controllers/content_items_controller_test.rb
test/presenters/content_item_presenter_test.rb
test/presenters/guide_presenter_test.rb
test/presenters/service_standard_presenter_test.rb
test/presenters/topic_presenter_test.rb
test/test_helper.rb

https://github.com/alphagov/rubocop-govuk/issues/73
Please see the commits for more details.

Remove RuboCop config and fix issues

---

.gitignore
Gemfile
Gemfile.lock
test/test_helper.rb

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
We should always monitor the amount of code that is exercised when
we run our tests.

Use SimpleCov to monitor code coverage

---

Dockerfile

Specify userid and groupid in the Dockerfile

---

.github/PULL_REQUEST_TEMPLATE.md

https://trello.com/c/LZctyIYq/3007-automatically-add-extra-instructions-to-dependabot-prs-for-rails-1

Add instructions for upgrading Rails

---

.github/PULL_REQUEST_TEMPLATE.md

https://trello.com/c/LZctyIYq/3007-automatically-add-extra-instructions-to-dependabot-prs-for-rails-1

Amend instructions for upgrading Rails
